language: php
php:
  - "7.4"
before_script:
  - composer install --no-interaction --prefer-source
  - php -S localhost:8080 public/index.php
script:
  - ./vendor/bin/behat
  - ./vendor/bin/phpunit tests
